en:
  errors:
    messages:
      secret_not_allowed_for_connector: "is not allowed for a Connector"
